/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedArreglosRouteImport } from './routes/_authenticated/arreglos'
import { Route as AuthenticatedCalleRouteImport } from './routes/_authenticated/calle'
import { Route as AuthenticatedContadoresRouteImport } from './routes/_authenticated/contadores'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedLetrasRouteImport } from './routes/_authenticated/letras'
import { Route as AuthenticatedMiembrosRouteImport } from './routes/_authenticated/miembros'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedSetlistsRouteImport } from './routes/_authenticated/setlists'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArreglosRoute = AuthenticatedArreglosRouteImport.update({
  id: '/arreglos',
  path: '/arreglos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalleRoute = AuthenticatedCalleRouteImport.update({
  id: '/calle',
  path: '/calle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContadoresRoute = AuthenticatedContadoresRouteImport.update({
  id: '/contadores',
  path: '/contadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLetrasRoute = AuthenticatedLetrasRouteImport.update({
  id: '/letras',
  path: '/letras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiembrosRoute = AuthenticatedMiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetlistsRoute = AuthenticatedSetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/arreglos': typeof AuthenticatedArreglosRoute
  '/calle': typeof AuthenticatedCalleRoute
  '/contadores': typeof AuthenticatedContadoresRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/letras': typeof AuthenticatedLetrasRoute
  '/miembros': typeof AuthenticatedMiembrosRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/setlists': typeof AuthenticatedSetlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/arreglos': typeof AuthenticatedArreglosRoute
  '/calle': typeof AuthenticatedCalleRoute
  '/contadores': typeof AuthenticatedContadoresRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/letras': typeof AuthenticatedLetrasRoute
  '/miembros': typeof AuthenticatedMiembrosRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/setlists': typeof AuthenticatedSetlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/arreglos': typeof AuthenticatedArreglosRoute
  '/_authenticated/calle': typeof AuthenticatedCalleRoute
  '/_authenticated/contadores': typeof AuthenticatedContadoresRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/letras': typeof AuthenticatedLetrasRoute
  '/_authenticated/miembros': typeof AuthenticatedMiembrosRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/setlists': typeof AuthenticatedSetlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/arreglos'
    | '/calle'
    | '/contadores'
    | '/inicio'
    | '/letras'
    | '/miembros'
    | '/repertorio'
    | '/setlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/arreglos'
    | '/calle'
    | '/contadores'
    | '/inicio'
    | '/letras'
    | '/miembros'
    | '/repertorio'
    | '/setlists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/arreglos'
    | '/_authenticated/calle'
    | '/_authenticated/contadores'
    | '/_authenticated/inicio'
    | '/_authenticated/letras'
    | '/_authenticated/miembros'
    | '/_authenticated/repertorio'
    | '/_authenticated/setlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arreglos': {
      id: '/_authenticated/arreglos'
      path: '/arreglos'
      fullPath: '/arreglos'
      preLoaderRoute: typeof AuthenticatedArreglosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calle': {
      id: '/_authenticated/calle'
      path: '/calle'
      fullPath: '/calle'
      preLoaderRoute: typeof AuthenticatedCalleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contadores': {
      id: '/_authenticated/contadores'
      path: '/contadores'
      fullPath: '/contadores'
      preLoaderRoute: typeof AuthenticatedContadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letras': {
      id: '/_authenticated/letras'
      path: '/letras'
      fullPath: '/letras'
      preLoaderRoute: typeof AuthenticatedLetrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/miembros': {
      id: '/_authenticated/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof AuthenticatedMiembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setlists': {
      id: '/_authenticated/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof AuthenticatedSetlistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedArreglosRoute: typeof AuthenticatedArreglosRoute
  AuthenticatedCalleRoute: typeof AuthenticatedCalleRoute
  AuthenticatedContadoresRoute: typeof AuthenticatedContadoresRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLetrasRoute: typeof AuthenticatedLetrasRoute
  AuthenticatedMiembrosRoute: typeof AuthenticatedMiembrosRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
  AuthenticatedSetlistsRoute: typeof AuthenticatedSetlistsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedArreglosRoute: AuthenticatedArreglosRoute,
  AuthenticatedCalleRoute: AuthenticatedCalleRoute,
  AuthenticatedContadoresRoute: AuthenticatedContadoresRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLetrasRoute: AuthenticatedLetrasRoute,
  AuthenticatedMiembrosRoute: AuthenticatedMiembrosRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
  AuthenticatedSetlistsRoute: AuthenticatedSetlistsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
